#!/usr/bin/env bash

# Run the tests.

: ${VIRTUAL_ENV:?"Invoke virtualenv with 'activate' first."}
cd $VIRTUAL_ENV/..

./database/init_db

echo "testing model.py"; python src/model.py
echo "testing page.py"; python src/page.py


