#!/usr/bin/env bash

# Run the tests.

: ${VIRTUAL_ENV:?"Invoke virtualenv with 'activate' first."}
cd $VIRTUAL_ENV/..

./database/init_db

echo " Testing model.py"; python src/model.py
echo " Testing page.py"; python src/page.py


