#!/usr/bin/env bash

# Initialize database and its tables if it doesn't already exist,
# and populate with default data (roles & demo course stuff for tests).
# Doesn't modify a database which has already been initialized.
# 
# sqlite3 version
#

: ${VIRTUAL_ENV:?"Invoke virtualenv with 'activate' first."}
cd $VIRTUAL_ENV/..
if [ ! -f database/sqlite3/umber.db ]; then
  sqlite3 database/sqlite3/umber.db < database/sqlite3/umber_sqlite3.sql
fi
python -c "import src.model; src.model.populate_db()"


