#!/usr/bin/env bash
#

# Is the project environment setup?
: ${UMBER_ROOT:?"Setup environment with 'source env/activate' first."}
cd $UMBER_ROOT   # Set the working folder to the project root.

# Initialize sqlite3 database and its tables if it doesn't already exist,
# and populate with default data (roles & demo course stuff for tests).
# Doesn't modify a database which has already been initialized.

if [ ! -f database/umber.db ]; then
  sqlite3 database/umber.db < database/umber.sql
fi

cd ./src
python -c "import model; model.populate_db()"
cd ..
