#!/usr/bin/env bash

# Is the project environment setup?
: ${UMBER_ROOT:?"Setup environment with 'source env/activate' first."}
cd $UMBER_ROOT   # Set the working folder to the project root.

# database/erd/make_png
#
# Create umber_db.png, an entity relatioship diagram (ERD) for the database
#
# Requires SqlFairy, i.e.
#   $ cpan install SQL::Translater; cpan install GraphViz
# See 
#   http://mancoosi.org/~abate/tags/sqlfairy
#   http://search.cpan.org/~frew/SQL-Translator/
#
# In the ERD diagram an arrow connecting two tables, e.g.
#
#     [Course] ---> [Registration]
#
# means that there is a one-to-many relationship between them, 
# for example that a course has many registrations, 
# i.e. the Registration table has a course_id foreign key.
#
# A solid black arrow indicates a required (non-null) foreign key,
# while an arrow outline represents an optional (may be null) relation.

cd database/erd
./sqlt-graph --from=SQLite \
            ../sqlite3/umber_sqlite3.sql > umber_sqlite3.png
echo "OK, database/erd/umber_sqlite3.png has been created."
